### ISSUE TITLE
error ketika simpan organisasi,

### ISSUE THREAD

**Issue by buruhsd** [mrizkir/eplanning#15]
`SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "OrgIDRPJMD" violates not-null constraint DETAIL: Failing row contains (uid5d9edaf3dd86d, null, uid5d9ec81494d8b, 1, Bendahara, BNDHR, semarang, Friska susan, 12345678, null, 2019, 2019-10-10 14:17:07, 2019-10-10 14:17:07). (SQL: insert into "tmOrg" ("OrgID", "UrsID", "OrgCd", "OrgNm", "OrgAlias", "NamaKepalaSKPD", "NIPKepalaSKPD", "Alamat", "Descr", "TA", "updated_at", "created_at") values (uid5d9edaf3dd86d, uid5d9ec81494d8b, 1, Bendahara, BNDHR, Friska susan, 12345678, jambi, ?, 2019, 2019-10-10 14:17:07, 2019-10-10 14:17:07))`

dapat error seperti di atas, itu kenapa ya? terima kashi

**Comment by mrizkir** [comment]
error ini diperoleh di file apa / atau saat menginputkan apa ?

**Comment by mrizkir** [comment]
OrgIDRPJMD kosong
